name: Bug Report
description: Report an issue to help us improve
title: "[BUG] Brief description"
labels: ["bug"]
assignees: 'expxx'
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for reporting!
        Please be as detailed as possible. For urgent issues, join our [Discord](https://discord.gg/9DxxWYDy9D).
        
  - type: input
    id: bug-title
    attributes:
      label: Brief Description
      description: One-line summary of the issue
      placeholder: e.g., "Server crashes when player joins"
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Exactly how to trigger the bug
      value: |
        1. 
        2. 
        3. 
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should normally happen
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens
      render: markdown
    validations:
      required: true
      
  - type: dropdown
    id: frequency
    attributes:
      label: Occurrence Frequency
      options:
        - Always
        - Sometimes
        - Rarely
        - Only once
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Software Version
      description: Exact version where bug occurs
      placeholder: e.g., 1.20.1, v2.5.0
    validations:
      required: true
      
  - type: checkboxes
    id: confirmations
    attributes:
      label: Verification
      options:
        - label: I've searched existing issues and this hasn't been reported
        - label: I've tested with the latest version
