// THIS IS AN EXAMPLE. YOU CANNOT USE TYPESCRIPT WHEN CONTRIBUTING TO THIS REPOSITORY. MUST BE
// JAVASCRIPT (ending in .js). IF YOU INSIST ON USING TS, BUILD OUT IN TYPESCRIPT AND COMPILE
// USING "tsc". SUBMIT THE COMPILED TYPESCRIPT. HOWEVER, WE STRONGLY RECOMMEND AGAINST THIS
// FOR READABILITY REASONS.
//
// THIS FILE IS NOT USED IN THE REPO, THIS FILE IS NOT INCLUDED IN THE EGG. THIS IS WHAT YOU 
// SHOULD RETURN FROM YOUR INSTALLER. USE THE PAPER INSTALLER AS AN EXAMPLE.

export default interface VersionResponse {
	sdk: {
		type: string,
		version: string
	},
	program: {
		eulaMsg: string | undefined,
		eulaFile: string | undefined,
		agreeData: string | undefined,
	},
	launch: string
}
